Add operator filter registry
traderjoe-xyz/launchpeg-v2 pull request #13
Opened 2022-12-16 15:08 UTC by Mathieu-Be

## Implementation of OpenSea's filter registry

This implements the filter registry from OpenSea, allowing the filtering of NFT marketplaces not enforcing royalties. After being blocked, contract addresses won't be able to get approvals or transfer NFTs anymore.

OpenSea will soon make royalties optional for NFT collections that are not supporting this filtering property.

I tried to summarize how it works below, but the original repo is worth a read: https://github.com/ProjectOpenSea/operator-filter-registry

### How it works

Launchpeg contracts will subscribe to OpenSea's blocklist through the `Operator Filter Registry`. On every `transferFrom`, the contract will ask the registry if the `msg.sender` is allowed to operate NFTs of the collection. It also blocks approvals.

By default, I made the contract subscribe to the OS blocklist (that currently has no addresses blocked on Avalanche), but it is possible to update and create our own list. In that case, our list should include the entire OS list. We can also completely disable it by updating the registry address to `address(0)`.

A contract can subscribe to another address blocklist, or have it's own. Both the contract and the contract owner are able to modify this through the registry.

![Operator Filter Registry](https://user-images.githubusercontent.com/85969303/208125845-dbc0ce1d-1e90-4cce-b3af-a3f975d24ce6.png)

## Extra modifications

- The version of ERC721A that we used don't have `approve` marked as virtual, so I couldn't overwrite it. I forked the code and changed that, diff can be found here: https://www.diffchecker.com/ED8HeKZ9. The latest version of the contract would have worked but they made a ton of other modifications.
- I had some contract size issues again so I had to remove a few errors types and reduce the number of compiler optimizations runs.
- I also had to bump the solidity version of the contracts as OS ones are `pragma solidity ^0.8.13`.

2022-12-16 20:02 UTC, 0x0Louis requested changes

2022-12-18 04:52 UTC, simsk87 approved these changes
looks good to me!

2022-12-19 14:09 UTC, Mathieu-Be commented on contracts/BaseLaunchpeg.sol
> +            address(registry) != address(0) && address(registry).code.length > 0
Yeah I guess they did it to be extra safe since it's meant to be deployed on many different chains. I took it directly from OS contracts.

2022-12-19 15:10 UTC, 0x0Louis commented on contracts/BaseLaunchpeg.sol
> +            address(registry) != address(0) && address(registry).code.length > 0
Looking at OS contracts, it seems like they don't do that explicit address(0) check? https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/src/OperatorFilterer.sol#L52-L59

2022-12-19 15:13 UTC, 0x0Louis approved these changes

2022-12-21 13:48 UTC, merged